### ISSUE TITLE
no output from codespell despite spell errors in the code

### ISSUE THREAD

**Issue by dpriskorn** [internetarchive/wcdimportbot#31]
![bild](https://user-images.githubusercontent.com/68460690/171398146-6d855346-e8ec-4118-ade7-44cf3ebb0eaa.png)
@cclauss do you know where to look up this obscure error code? I searched a little and found nothing.

**Comment by cclauss** [comment]
If you fix those four typos, do you still get the error?

successfull ==> successful — The first is a typo which needs to be changed to the second.

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by dpriskorn** [comment]
When I run codespell on the codebase I get no errors or output.
![bild](https://user-images.githubusercontent.com/68460690/171557933-41e08bbf-784f-429a-b8ce-a229913b21a0.png)
Any ideas why?

**Comment by dpriskorn** [comment]
This works 
![bild](https://user-images.githubusercontent.com/68460690/171599510-5e6cfc14-81ac-49c3-b413-2609ff737570.png)

**Comment by cclauss** [comment]
codespell --ignore-words-list=successfull

**Comment by cclauss** [comment]
I ran into the same trouble on OpenLIbrary today so there might be a change in codespell.

You can always do `git commit --no-verify ...` if you have pre-commit installed locally.
